apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
      name: wazuh-agent
    spec:
      hostPID: true
      containers:
      - name: wazuh-agent
        image: friquetito/falco-wazuh
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1
            memory: 2Gi
        env:
        - name: wazuh_manager
          value: ""
        - name: SYSDIG_SKIP_LOAD
          value: "true"
        - name: wazuh_groups
          value: "daemonset" 
        - name: wazuh_password
          valueFrom:
            secretKeyRef:
                name: wazuh-password
                key: password
        volumeMounts:
        - mountPath: /var/run
          name: var-run
        - mountPath: /host/dev
          name: dev
        - mountPath: /host/sys
          name: sys
          readOnly: true
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/etc
          name: etc
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-socket-mount
        - mountPath: /host/var/run/docker.sock
          name: docker-socket-mount
        - mountPath: /host/boot
          name: boot
          readOnly: true
        - mountPath: /host/usr
          name: usr
          readOnly: true
        - mountPath: /host/lib/modules
          name: modules
          readOnly: true
        - mountPath: /host/var/log
          name: log
          readOnly: true
      volumes:
      - name: docker-socket-mount
        hostPath:
          path: /var/run/docker.sock
      - name: var-run
        hostPath:
          path: /var/run
      - name: dev
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: proc
        hostPath:
          path: /proc
      - name: etc
        hostPath:
          path: /etc
      - name: boot
        hostPath:
          path: /boot
      - name: usr
        hostPath:
          path: /usr
      - name: modules
        hostPath:
          path: /lib/modules
      - name: log
        hostPath:
          path: /var/logs